const products=[
 {id:1,name:'Pão de Fermentação Natural',category:'paes',price:18,description:'Casca crocante e miolo macio. 500g.',image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80'},
 {id:2,name:'Croissant de Manteiga',category:'paes',price:11.5,description:'Folhado, dourado e assado na hora.',image:'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80'},
 {id:3,name:'Cinnamon Roll',category:'doces',price:13.9,description:'Canela, massa macia e glacê de baunilha.',image:'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=600&q=80'},
 {id:4,name:'Cappuccino da Casa',category:'cafe',price:12,description:'Café especial, leite cremoso e canela.',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80'},
 {id:5,name:'Focaccia de Alecrim',category:'paes',price:16.5,description:'Azeite, sal grosso e ervas frescas.',image:'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=600&q=80'},
 {id:6,name:'Bolo de Cenoura',category:'doces',price:14,description:'Fatia generosa com chocolate cremoso.',image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80'},
 {id:7,name:'Kit Café da Manhã',category:'kits',price:68,description:'Pães, doces, frutas e café para duas pessoas.',image:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80'},
 {id:8,name:'Café Coado',category:'cafe',price:8,description:'Grãos brasileiros moídos na hora.',image:'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80'}
];
const cart=[];const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const grid=document.querySelector('#product-grid');
function drawProducts(category='todos'){const list=category==='todos'?products:products.filter(p=>p.category===category);grid.innerHTML=list.map(p=>`<article class="product"><div class="product-image" style="background-image:url('${p.image}')"></div><div class="details"><p>${p.category.toUpperCase()}</p><h3>${p.name}</h3><div class="description">${p.description}</div><div class="bottom"><span class="price">${money(p.price)}</span><button class="add" data-id="${p.id}" aria-label="Adicionar ${p.name}">+</button></div></div></article>`).join('')}
function add(id){const product=products.find(p=>p.id===id),found=cart.find(p=>p.id===id);found?found.q++:cart.push({...product,q:1});drawCart()}
function quantity(id,change){const item=cart.find(p=>p.id===id);item.q+=change;if(!item.q)cart.splice(cart.indexOf(item),1);drawCart()}
function drawCart(){const count=cart.reduce((a,p)=>a+p.q,0),total=cart.reduce((a,p)=>a+p.price*p.q,0);document.querySelector('#bag-count').textContent=count;document.querySelector('#total').textContent=money(total);document.querySelector('#checkout').disabled=!cart.length;document.querySelector('#cart-items').innerHTML=cart.length?cart.map(p=>`<div class="item"><h3>${p.name}</h3><div class="qty"><button data-id="${p.id}" data-change="-1">−</button><span>${p.q}</span><button data-id="${p.id}" data-change="1">+</button></div><p>${money(p.q*p.price)}</p></div>`).join(''):'<p class="empty">Sua sacola ainda está vazia.<br />A vitrine está esperando por você.</p>'}
function toggle(open){document.querySelector('#cart').classList.toggle('open',open);document.querySelector('#shade').classList.toggle('show',open);document.querySelector('#cart').setAttribute('aria-hidden',!open)}
document.querySelectorAll('.categories button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.categories .active').classList.remove('active');b.classList.add('active');drawProducts(b.dataset.category)}));grid.addEventListener('click',e=>{if(e.target.matches('.add'))add(+e.target.dataset.id)});document.querySelector('#cart-items').addEventListener('click',e=>{if(e.target.dataset.change)quantity(+e.target.dataset.id,+e.target.dataset.change)});document.querySelector('#open-cart').onclick=()=>toggle(true);document.querySelector('#close-cart').onclick=()=>toggle(false);document.querySelector('#shade').onclick=()=>toggle(false);document.querySelector('#checkout').onclick=()=>{const list=cart.map(p=>`• ${p.q}x ${p.name} — ${money(p.price*p.q)}`).join('%0A'),total=cart.reduce((a,p)=>a+p.price*p.q,0);open(`https://wa.me/5516997863346?text=Olá!%20Quero%20fazer%20este%20pedido:%0A%0A${list}%0A%0A*Total:%20${money(total)}*%0A%0ARetirada%20ou%20entrega:`,'_blank')};drawProducts();
